Let rqw customize the terminate signal
Doist/rqw pull request #1
Opened 2020-04-29 22:23 UTC by imankulov

The default behavior of rqw is send SIGTERM, and then SIGKILL signals.
Although in Python, it's easier to catch SIGINT (2), because it's
automatically converted to a KeyboardInterput exception, and you don't
need to set up a specific signal handler to process it.

This commit adds an option "-signal" that allows to override the default
SIGTERM (15) with a different signal number.

2020-04-29 22:32 UTC, imankulov commented
I tested the work of rqw with the following script

```python
#!/usr/bin/env python
import os
import time

while True:
    try:
        time.sleep(1)
        print(os.getpid())
    except KeyboardInterrupt:
        print(os.getpid(), "terminated with with SIGINT")
        raise SystemExit()
```

To see the output of the script, I changed the code in the `internal/rqw/pw.go` as this (not included in the commit).

```diff
diff --git a/internal/rqw/pw.go b/internal/rqw/pw.go
index 3253329..221d0b0 100644
--- a/internal/rqw/pw.go
+++ b/internal/rqw/pw.go
@@ -6,6 +6,7 @@ import (
        "fmt"
        "log"
        "math/rand"
+       "os"
        "os/exec"
        "sync"
        "sync/atomic"
@@ -182,6 +183,7 @@ func (t *Troop) SpawnProcess() error {
 doStart:
        cmd := exec.Command(t.path)
        cmd.Stderr = &prefixSuffixSaver{N: 32 << 10}
+       cmd.Stdout = os.Stdout
        cmd.SysProcAttr = sysProcAttr()
        if err := cmd.Start(); err != nil {
                t.gate.Unlock()
```

Running it with the following command

```
./rqw -threshold 1 -delay 5s -queue foo -signal 2 -worker ./test.py
```

To start some processes, I populate the local redis queue (from IPython)

```
In [1]: import redis

In [2]: r = redis.Redis()

In [3]: for i in range(10000): r.zadd('foo', {i: i})
```

This spawned several processes, like this.

```
2020/04/29 23:28:36 process "./test.py" [40985] spawned
40953
40969
...
```

Then, to scale down, I removed the key


```
In [4]: r.delete('foo')
Out[4]: 1
```

Got the message, as expected

```
2020/04/29 23:29:51 terminate "./test.py" [40969]
40969 terminated with with SIGINT
...
```

2020-04-30 10:49 UTC, artyom commented
@imankulov you'd also want to update Shutdown method: https://github.com/Doist/rqw/blob/bd885af393916eb992c120f5adfbd4c5bb411931/internal/rqw/pw.go#L226-L228

Also note that it's worth supporting TERM as a normal termination signal. For example on ECS there's no way to override this.

2020-04-30 10:50 UTC, artyom requested changes
Please see my note about Shutdown method.

2020-05-05 09:54 UTC, imankulov commented
> Also note that it's worth supporting TERM as a normal termination signal. For example on ECS there's no way to override this.

That makes total sense. Let's close it down in favor of having proper SIGTERM processing in spawned processes.

2020-05-05 09:54 UTC, closed without merging